version: '3.7'

volumes:
    mirror-t0-packages:

networks:
    mirror-t0-network:
        name: mirror-t0-network
        external: true

services:
    mirror-tier0:
        build:
            context: .
            dockerfile: ./DockerFiles/mirror/Dockerfile
            # ulimits:
            #     nproc: 65535
            #     nofile:
            #         soft: 65536
            #         hard: 65536
        ports:
            - "8000:80"
            - "4430:443"
        networks:
            mirror-t0-network:
                aliases:
                    - tier0.archlinux.life
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "./DockerFiles/mirror/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - mirror-t0-packages:/srv/http
    rsync-tier0:
        build:
            context: .
            dockerfile: ./DockerFiles/rsync/Dockerfile
        volumes:
            - "./DockerFiles/rsync/rsyncd.conf:/etc/rsync/rsyncd.conf"
            - "./DockerFiles/rsync/share.list:/share.list"
            - mirror-t0-packages:/srv/http
        networks:
            mirror-t0-network:
        ports:
            - "873:873"
        restart: always