---
all:
  children:
    all_mirrors:
      children:
        mirrors:
          children:
            tier0:
              hosts:
                tier0:
            tier1:
              hosts:
                tier1:
            #tier2:
            #  hosts:
            #    tier2: