version: '3.7'

services:
    mirror:
        build:
            context: .
            dockerfile: ./DockerFiles/Dockerfile
            # ulimits:
            #     nproc: 65535
            #     nofile:
            #         soft: 65536
            #         hard: 65536
        ports:
            - "80:80"
            - "443:443"
        networks:
            - default
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "./DockerFiles/nginx/nginx.conf:/etc/nginx/nginx.conf"