---
- name: Create Tier1 Network
  community.docker.docker_network:
    name: mirror-t1-network
    state: present
    internal: false
    scope: global


# - name: Remove all but selected list of containers
#   community.docker.docker_network:
#     name: mirror-network
#     connected:
#       - tier0-mirror
#       - tier1-mirror
# #           - tier2-mirror

- name: Start the mirror
  command: docker-compose -f /home/anton/github/arch-linux-containers/docker/tier1/docker-compose.yml up --remove-orphans -d
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output

    # - name: Verify that web and db services are running
    #     ansible.builtin.assert:
    #         that:
    #             - "output.services.web.flask_web_1.state.running"
    #             - "output.services.db.flask_db_1.state.running"
