version: '3.7'

volumes:
    mirror-t1-packages:

networks:
    mirror-t1-network:
        name: mirror-t1-network
        external: true

services:
    mirror-tier1:
        build:
            context: .
            dockerfile: ./DockerFiles/mirror/Dockerfile
            # ulimits:
            #     nproc: 65535
            #     nofile:
            #         soft: 65536
            #         hard: 65536
        ports:
            - "8001:80"
            - "4431:443"
        networks:
            mirror-t1-network:
                aliases:
                    - tier1.archlinux.life
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "./DockerFiles/mirror/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - mirror-t1-packages:/srv/http
    rsync-tier1:
        build:
            context: .
            dockerfile: ./DockerFiles/rsync/Dockerfile
        volumes:
            - "./DockerFiles/rsync/rsyncd.conf:/etc/rsync/rsyncd.conf"
            - "./DockerFiles/rsync/share.list:/share.list"
            - mirror-t1-packages:/srv/http
        networks:
            mirror-t1-network:
        restart: always
        environment:
            TIER0_HOST: tier0.archlinux.life
            TIER0_PORT: 873